In [23]:
import statistics
import pandas as pd
import numpy as np

Question 1
What is the result of the following code?

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
c = a + b
print(c)
#[5 7 9]

[5 7 9]


Question 2
Create a numpy array of 10 zeros. and reshape it to (2, 5)

In [6]:
my_array = np.zeros((10,), dtype=int)
my_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
my_array = my_array.reshape(2,5)
my_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Question 3
Find Mean, Mode, Median, Standard Deviation of the following data:

In [24]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [25]:
Mean = np.mean(data)
Mean

10.5

In [10]:
Median = np.median(data)
Median

10.5

In [13]:
Mode= statistics.mode(data)
Mode

1

In [17]:
Standard_deviation = np.std(data)
Standard_deviation


2.581988897471611

Question 4
create a 6x6 numpy array with random values and find the min and max values

In [15]:
myArray = np.random.random((6,6))
print(myArray) 
myArraymin, myArraymax = myArray.min(), myArray.max()
print("Minimum and Maximum Values:")
print(myArraymin, myArraymax)


[[0.93480076 0.48117758 0.05074889 0.7944722  0.77125966 0.78637155]
 [0.05399935 0.77337995 0.92153872 0.23585683 0.6888827  0.57893141]
 [0.75109833 0.69494523 0.03333476 0.68709949 0.46927758 0.14598365]
 [0.23632281 0.66301798 0.70678036 0.24148204 0.82948481 0.42349781]
 [0.86032868 0.9344951  0.63402743 0.30305419 0.70462207 0.56778614]
 [0.27918634 0.34240094 0.08953663 0.61048351 0.10010969 0.22298612]]
Minimum and Maximum Values:
0.03333475561279342 0.9348007586987082


Question 5
create a 3D numpy array and reshape it to 2D

In [20]:
_array = np.array([[[8,8], [75, 4]], [[10, 2], [20, 76]],[[76,33],[20,19]]])
print("3-d array:",_array)

3-d array: [[[ 8  8]
  [75  4]]

 [[10  2]
  [20 76]]

 [[76 33]
  [20 19]]]


In [22]:
#reshape to 2D
newarr = _array.reshape(4, 3)

print("2-d array:",newarr)

2-d array: [[ 8  8 75]
 [ 4 10  2]
 [20 76 76]
 [33 20 19]]


Question 6
create 1D array from this data

    data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
n = np.array(data)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
